# Generated by Django 6.0.5 on 2026-05-11 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('labor', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('work_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.labor')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lot')),
                ('lot_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lotcolor')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.operation')),
                ('sub_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.suboperation')),
            ],
            options={
                'indexes': [models.Index(fields=['work_date'], name='production__work_da_bc0e40_idx'), models.Index(fields=['labor'], name='production__labor_i_a79f95_idx'), models.Index(fields=['lot'], name='production__lot_id_fbed15_idx'), models.Index(fields=['operation'], name='production__operati_9bf9fb_idx')],
            },
        ),
    ]
