# Generated by Django 6.0.5 on 2026-05-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_workentry_lot_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
