# Generated by Django 6.0.5 on 2026-06-08 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(unique=True, verbose_name='Sr No')),
                ('challan_no', models.CharField(max_length=100, verbose_name='Challan No')),
                ('date', models.DateField(verbose_name='Date')),
                ('delivery_party', models.CharField(max_length=255, verbose_name='Delivery Party')),
                ('buyer_party', models.CharField(max_length=255, verbose_name='Buyer Party')),
                ('article_no', models.CharField(max_length=100, verbose_name='Article No')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sr_no'],
            },
        ),
        migrations.CreateModel(
            name='InwardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=100, verbose_name='Roll No')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Color')),
                ('meters', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Meters')),
                ('inward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inward.inward')),
            ],
        ),
    ]
