# Generated by Django 6.0.5 on 2026-06-13 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labor',
            name='login_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LaborSetupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_tokens', to='labor.labor')),
            ],
        ),
    ]
