# Generated by Django 6.0.5 on 2026-06-05 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=200, verbose_name='Sample Name/Code')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('pieces', models.PositiveIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('work_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_work', to='labor.labor')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.party')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
                'indexes': [models.Index(fields=['work_date'], name='samples_sam_work_da_b8f27e_idx'), models.Index(fields=['party'], name='samples_sam_party_i_4468a4_idx'), models.Index(fields=['labor'], name='samples_sam_labor_i_c690dc_idx')],
            },
        ),
    ]
