# Generated by Django 6.0.5 on 2026-06-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='pieces',
        ),
        migrations.AddField(
            model_name='sample',
            name='total_pieces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SampleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('pieces', models.PositiveIntegerField(default=1)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='samples.sample')),
            ],
        ),
    ]
