# Generated by Django 6.0.5 on 2026-06-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_remove_sample_color_remove_sample_pieces_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleColor',
        ),
    ]
