# Generated by Django 6.0.5 on 2026-06-07 12:54

from django.db import migrations


def fix_5th_operation(apps, schema_editor):
    Operation = apps.get_model('operations', 'Operation')
    try:
        op = Operation.objects.get(name='5th')
        op.has_sub_operations = False
        op.save()
    except Operation.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_5th_operation),
    ]
