# Generated by Django 6.0.5 on 2026-06-07 13:03

from django.db import migrations


def fix_sm_operation(apps, schema_editor):
    Operation = apps.get_model('operations', 'Operation')
    try:
        op = Operation.objects.get(name='SM')
        op.has_sub_operations = False
        op.save()
    except Operation.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_fix_5th_sub_ops'),
    ]

    operations = [
        migrations.RunPython(fix_sm_operation),
    ]
